/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades/index'
import { Route as StrategyIndexRouteImport } from './routes/strategy/index'
import { Route as HmmIndexRouteImport } from './routes/hmm/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as StrategyCreateRouteImport } from './routes/strategy.create'
import { Route as StrategyIdRouteImport } from './routes/strategy/$id'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiStrategyRouteImport } from './routes/api/strategy'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as StrategyIdBacktestRouteImport } from './routes/strategy_.$id.backtest'
import { Route as ApiStrategyTradeActionsRouteImport } from './routes/api/strategy/tradeActions'
import { Route as ApiStrategySignalsRouteImport } from './routes/api/strategy/signals'
import { Route as ApiStrategyListRouteImport } from './routes/api/strategy/list'
import { Route as ApiStrategyBacktestRouteImport } from './routes/api/strategy/backtest'
import { Route as ApiStrategyIdRouteImport } from './routes/api/strategy/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiUserFavoritesIndexRouteImport } from './routes/api/user/favorites/index'
import { Route as ApiStrategyIdNotificationRouteImport } from './routes/api/strategy/$id/notification'
import { Route as ApiStrategyIdBacktestRouteImport } from './routes/api/strategy/$id/backtest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyIndexRoute = StrategyIndexRouteImport.update({
  id: '/strategy/',
  path: '/strategy/',
  getParentRoute: () => rootRouteImport,
} as any)
const HmmIndexRoute = HmmIndexRouteImport.update({
  id: '/hmm/',
  path: '/hmm/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyCreateRoute = StrategyCreateRouteImport.update({
  id: '/strategy/create',
  path: '/strategy/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyIdRoute = StrategyIdRouteImport.update({
  id: '/strategy/$id',
  path: '/strategy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategyRoute = ApiStrategyRouteImport.update({
  id: '/api/strategy',
  path: '/api/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyIdBacktestRoute = StrategyIdBacktestRouteImport.update({
  id: '/strategy_/$id/backtest',
  path: '/strategy/$id/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategyTradeActionsRoute = ApiStrategyTradeActionsRouteImport.update({
  id: '/tradeActions',
  path: '/tradeActions',
  getParentRoute: () => ApiStrategyRoute,
} as any)
const ApiStrategySignalsRoute = ApiStrategySignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => ApiStrategyRoute,
} as any)
const ApiStrategyListRoute = ApiStrategyListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ApiStrategyRoute,
} as any)
const ApiStrategyBacktestRoute = ApiStrategyBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => ApiStrategyRoute,
} as any)
const ApiStrategyIdRoute = ApiStrategyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStrategyRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserFavoritesIndexRoute = ApiUserFavoritesIndexRouteImport.update({
  id: '/api/user/favorites/',
  path: '/api/user/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategyIdNotificationRoute =
  ApiStrategyIdNotificationRouteImport.update({
    id: '/notification',
    path: '/notification',
    getParentRoute: () => ApiStrategyIdRoute,
  } as any)
const ApiStrategyIdBacktestRoute = ApiStrategyIdBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => ApiStrategyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/strategy': typeof ApiStrategyRouteWithChildren
  '/api/trades': typeof ApiTradesRoute
  '/strategy/$id': typeof StrategyIdRoute
  '/strategy/create': typeof StrategyCreateRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hmm/': typeof HmmIndexRoute
  '/strategy/': typeof StrategyIndexRoute
  '/trades/': typeof TradesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/strategy/$id': typeof ApiStrategyIdRouteWithChildren
  '/api/strategy/backtest': typeof ApiStrategyBacktestRoute
  '/api/strategy/list': typeof ApiStrategyListRoute
  '/api/strategy/signals': typeof ApiStrategySignalsRoute
  '/api/strategy/tradeActions': typeof ApiStrategyTradeActionsRoute
  '/strategy/$id/backtest': typeof StrategyIdBacktestRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/api/strategy/$id/backtest': typeof ApiStrategyIdBacktestRoute
  '/api/strategy/$id/notification': typeof ApiStrategyIdNotificationRoute
  '/api/user/favorites/': typeof ApiUserFavoritesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/strategy': typeof ApiStrategyRouteWithChildren
  '/api/trades': typeof ApiTradesRoute
  '/strategy/$id': typeof StrategyIdRoute
  '/strategy/create': typeof StrategyCreateRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/hmm': typeof HmmIndexRoute
  '/strategy': typeof StrategyIndexRoute
  '/trades': typeof TradesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/strategy/$id': typeof ApiStrategyIdRouteWithChildren
  '/api/strategy/backtest': typeof ApiStrategyBacktestRoute
  '/api/strategy/list': typeof ApiStrategyListRoute
  '/api/strategy/signals': typeof ApiStrategySignalsRoute
  '/api/strategy/tradeActions': typeof ApiStrategyTradeActionsRoute
  '/strategy/$id/backtest': typeof StrategyIdBacktestRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/api/strategy/$id/backtest': typeof ApiStrategyIdBacktestRoute
  '/api/strategy/$id/notification': typeof ApiStrategyIdNotificationRoute
  '/api/user/favorites': typeof ApiUserFavoritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/strategy': typeof ApiStrategyRouteWithChildren
  '/api/trades': typeof ApiTradesRoute
  '/strategy/$id': typeof StrategyIdRoute
  '/strategy/create': typeof StrategyCreateRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/hmm/': typeof HmmIndexRoute
  '/strategy/': typeof StrategyIndexRoute
  '/trades/': typeof TradesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/strategy/$id': typeof ApiStrategyIdRouteWithChildren
  '/api/strategy/backtest': typeof ApiStrategyBacktestRoute
  '/api/strategy/list': typeof ApiStrategyListRoute
  '/api/strategy/signals': typeof ApiStrategySignalsRoute
  '/api/strategy/tradeActions': typeof ApiStrategyTradeActionsRoute
  '/strategy_/$id/backtest': typeof StrategyIdBacktestRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/api/strategy/$id/backtest': typeof ApiStrategyIdBacktestRoute
  '/api/strategy/$id/notification': typeof ApiStrategyIdNotificationRoute
  '/api/user/favorites/': typeof ApiUserFavoritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/strategy'
    | '/api/trades'
    | '/strategy/$id'
    | '/strategy/create'
    | '/auth/'
    | '/dashboard/'
    | '/hmm/'
    | '/strategy/'
    | '/trades/'
    | '/api/auth/$'
    | '/api/strategy/$id'
    | '/api/strategy/backtest'
    | '/api/strategy/list'
    | '/api/strategy/signals'
    | '/api/strategy/tradeActions'
    | '/strategy/$id/backtest'
    | '/auth/login/'
    | '/auth/register/'
    | '/api/strategy/$id/backtest'
    | '/api/strategy/$id/notification'
    | '/api/user/favorites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/strategy'
    | '/api/trades'
    | '/strategy/$id'
    | '/strategy/create'
    | '/auth'
    | '/dashboard'
    | '/hmm'
    | '/strategy'
    | '/trades'
    | '/api/auth/$'
    | '/api/strategy/$id'
    | '/api/strategy/backtest'
    | '/api/strategy/list'
    | '/api/strategy/signals'
    | '/api/strategy/tradeActions'
    | '/strategy/$id/backtest'
    | '/auth/login'
    | '/auth/register'
    | '/api/strategy/$id/backtest'
    | '/api/strategy/$id/notification'
    | '/api/user/favorites'
  id:
    | '__root__'
    | '/'
    | '/api/strategy'
    | '/api/trades'
    | '/strategy/$id'
    | '/strategy/create'
    | '/auth/'
    | '/dashboard/'
    | '/hmm/'
    | '/strategy/'
    | '/trades/'
    | '/api/auth/$'
    | '/api/strategy/$id'
    | '/api/strategy/backtest'
    | '/api/strategy/list'
    | '/api/strategy/signals'
    | '/api/strategy/tradeActions'
    | '/strategy_/$id/backtest'
    | '/auth/login/'
    | '/auth/register/'
    | '/api/strategy/$id/backtest'
    | '/api/strategy/$id/notification'
    | '/api/user/favorites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStrategyRoute: typeof ApiStrategyRouteWithChildren
  ApiTradesRoute: typeof ApiTradesRoute
  StrategyIdRoute: typeof StrategyIdRoute
  StrategyCreateRoute: typeof StrategyCreateRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  HmmIndexRoute: typeof HmmIndexRoute
  StrategyIndexRoute: typeof StrategyIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  StrategyIdBacktestRoute: typeof StrategyIdBacktestRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  ApiUserFavoritesIndexRoute: typeof ApiUserFavoritesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/': {
      id: '/strategy/'
      path: '/strategy'
      fullPath: '/strategy/'
      preLoaderRoute: typeof StrategyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmm/': {
      id: '/hmm/'
      path: '/hmm'
      fullPath: '/hmm/'
      preLoaderRoute: typeof HmmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/create': {
      id: '/strategy/create'
      path: '/strategy/create'
      fullPath: '/strategy/create'
      preLoaderRoute: typeof StrategyCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/$id': {
      id: '/strategy/$id'
      path: '/strategy/$id'
      fullPath: '/strategy/$id'
      preLoaderRoute: typeof StrategyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategy': {
      id: '/api/strategy'
      path: '/api/strategy'
      fullPath: '/api/strategy'
      preLoaderRoute: typeof ApiStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy_/$id/backtest': {
      id: '/strategy_/$id/backtest'
      path: '/strategy/$id/backtest'
      fullPath: '/strategy/$id/backtest'
      preLoaderRoute: typeof StrategyIdBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategy/tradeActions': {
      id: '/api/strategy/tradeActions'
      path: '/tradeActions'
      fullPath: '/api/strategy/tradeActions'
      preLoaderRoute: typeof ApiStrategyTradeActionsRouteImport
      parentRoute: typeof ApiStrategyRoute
    }
    '/api/strategy/signals': {
      id: '/api/strategy/signals'
      path: '/signals'
      fullPath: '/api/strategy/signals'
      preLoaderRoute: typeof ApiStrategySignalsRouteImport
      parentRoute: typeof ApiStrategyRoute
    }
    '/api/strategy/list': {
      id: '/api/strategy/list'
      path: '/list'
      fullPath: '/api/strategy/list'
      preLoaderRoute: typeof ApiStrategyListRouteImport
      parentRoute: typeof ApiStrategyRoute
    }
    '/api/strategy/backtest': {
      id: '/api/strategy/backtest'
      path: '/backtest'
      fullPath: '/api/strategy/backtest'
      preLoaderRoute: typeof ApiStrategyBacktestRouteImport
      parentRoute: typeof ApiStrategyRoute
    }
    '/api/strategy/$id': {
      id: '/api/strategy/$id'
      path: '/$id'
      fullPath: '/api/strategy/$id'
      preLoaderRoute: typeof ApiStrategyIdRouteImport
      parentRoute: typeof ApiStrategyRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/favorites/': {
      id: '/api/user/favorites/'
      path: '/api/user/favorites'
      fullPath: '/api/user/favorites/'
      preLoaderRoute: typeof ApiUserFavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategy/$id/notification': {
      id: '/api/strategy/$id/notification'
      path: '/notification'
      fullPath: '/api/strategy/$id/notification'
      preLoaderRoute: typeof ApiStrategyIdNotificationRouteImport
      parentRoute: typeof ApiStrategyIdRoute
    }
    '/api/strategy/$id/backtest': {
      id: '/api/strategy/$id/backtest'
      path: '/backtest'
      fullPath: '/api/strategy/$id/backtest'
      preLoaderRoute: typeof ApiStrategyIdBacktestRouteImport
      parentRoute: typeof ApiStrategyIdRoute
    }
  }
}

interface ApiStrategyIdRouteChildren {
  ApiStrategyIdBacktestRoute: typeof ApiStrategyIdBacktestRoute
  ApiStrategyIdNotificationRoute: typeof ApiStrategyIdNotificationRoute
}

const ApiStrategyIdRouteChildren: ApiStrategyIdRouteChildren = {
  ApiStrategyIdBacktestRoute: ApiStrategyIdBacktestRoute,
  ApiStrategyIdNotificationRoute: ApiStrategyIdNotificationRoute,
}

const ApiStrategyIdRouteWithChildren = ApiStrategyIdRoute._addFileChildren(
  ApiStrategyIdRouteChildren,
)

interface ApiStrategyRouteChildren {
  ApiStrategyIdRoute: typeof ApiStrategyIdRouteWithChildren
  ApiStrategyBacktestRoute: typeof ApiStrategyBacktestRoute
  ApiStrategyListRoute: typeof ApiStrategyListRoute
  ApiStrategySignalsRoute: typeof ApiStrategySignalsRoute
  ApiStrategyTradeActionsRoute: typeof ApiStrategyTradeActionsRoute
}

const ApiStrategyRouteChildren: ApiStrategyRouteChildren = {
  ApiStrategyIdRoute: ApiStrategyIdRouteWithChildren,
  ApiStrategyBacktestRoute: ApiStrategyBacktestRoute,
  ApiStrategyListRoute: ApiStrategyListRoute,
  ApiStrategySignalsRoute: ApiStrategySignalsRoute,
  ApiStrategyTradeActionsRoute: ApiStrategyTradeActionsRoute,
}

const ApiStrategyRouteWithChildren = ApiStrategyRoute._addFileChildren(
  ApiStrategyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStrategyRoute: ApiStrategyRouteWithChildren,
  ApiTradesRoute: ApiTradesRoute,
  StrategyIdRoute: StrategyIdRoute,
  StrategyCreateRoute: StrategyCreateRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HmmIndexRoute: HmmIndexRoute,
  StrategyIndexRoute: StrategyIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  StrategyIdBacktestRoute: StrategyIdBacktestRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  ApiUserFavoritesIndexRoute: ApiUserFavoritesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
